global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_app'
    static_configs:
      - targets: ['host.docker.internal:3000'] # Replace with your Node.js application's IP address and port
